//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class archive
    {
        public System.DateTime date { get; set; }
        public double benzin { get; set; }
        public double motorin { get; set; }
        public double otogaz { get; set; }
    }
}
