//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilceler
    {
        public int IlceID { get; set; }
        public Nullable<int> IlID { get; set; }
        public string Ilce { get; set; }
        public string Ilceen { get; set; }
        public string Ilceop { get; set; }
        public string Ilcebp { get; set; }
    
        public virtual Iller Iller { get; set; }
        public virtual BP BP { get; set; }
        public virtual Opet Opet { get; set; }
        public virtual Shell Shell { get; set; }
        public virtual Total Total { get; set; }
        public virtual turkPetrol turkPetrol { get; set; }
    }
}
