//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Iller()
        {
            this.Ilceler = new HashSet<Ilceler>();
        }
    
        public int IlID { get; set; }
        public string Il { get; set; }
        public string Ilen { get; set; }
        public string Ilop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ilceler> Ilceler { get; set; }
    }
}
