//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Total
    {
        public int IlceID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> benzin { get; set; }
        public Nullable<double> motorin { get; set; }
        public Nullable<double> otogaz { get; set; }
        public string ilce { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
    }
}
